/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFrame;

import asrama.DataKamar;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class CreateDataKamar extends javax.swing.JFrame {

    /**
     * Creates new form CreateDataKamar
     */
    public CreateDataKamar() {
        initComponents();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Back = new javax.swing.JButton();
        LabelNoKamar = new javax.swing.JLabel();
        LabelLantai = new javax.swing.JLabel();
        LabelFasilitas = new javax.swing.JLabel();
        LabelHarga = new javax.swing.JLabel();
        FasilitasBox = new javax.swing.JTextField();
        Create = new javax.swing.JButton();
        LantaiBox = new javax.swing.JComboBox<>();
        NoKamarBox = new javax.swing.JComboBox<>();
        HargaBox = new javax.swing.JComboBox<>();
        CreateDataKamar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Back.setBackground(new java.awt.Color(204, 255, 255));
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 490, 90, 30));

        LabelNoKamar.setText("No.Kamar");
        getContentPane().add(LabelNoKamar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 120, 30));

        LabelLantai.setText("Lantai");
        getContentPane().add(LabelLantai, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 100, 30));

        LabelFasilitas.setText("Fasilitas");
        getContentPane().add(LabelFasilitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 90, 30));

        LabelHarga.setText("Harga");
        getContentPane().add(LabelHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 80, 30));
        getContentPane().add(FasilitasBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 180, 30));

        Create.setBackground(new java.awt.Color(204, 255, 204));
        Create.setText("Create");
        Create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateActionPerformed(evt);
            }
        });
        getContentPane().add(Create, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 270, 100, 40));

        LantaiBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        getContentPane().add(LantaiBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 180, 30));

        NoKamarBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "K01", "K02", "K03", "K04", "K05", "K06", "K07", "K08", "K09", "K10" }));
        NoKamarBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoKamarBoxActionPerformed(evt);
            }
        });
        getContentPane().add(NoKamarBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 180, 30));

        HargaBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "350000", "500000", "750000", "1000000" }));
        getContentPane().add(HargaBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, 180, 30));

        CreateDataKamar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/4.jpg"))); // NOI18N
        CreateDataKamar.setText("jLabel1");
        CreateDataKamar.setPreferredSize(new java.awt.Dimension(500, 530));
        getContentPane().add(CreateDataKamar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        AwalCRUD_DataKamar ADK = new AwalCRUD_DataKamar();
        this.dispose();
        ADK.setVisible(true);
    }//GEN-LAST:event_BackActionPerformed

    private void CreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateActionPerformed
        // TODO add your handling code here:
        String no_kamar = (String) NoKamarBox.getSelectedItem();
        String lantai = (String) LantaiBox.getSelectedItem();
        String fasilitas = FasilitasBox.getText().trim();  
        int harga = Integer.parseInt(String.valueOf(HargaBox.getSelectedItem()));

        if (fasilitas.isEmpty()) {
            // Notifikasi jika fasilitas kosong
            JOptionPane.showMessageDialog(null, "Fasilitas tidak boleh kosong.", "Peringatan", JOptionPane.WARNING_MESSAGE);
        } else {
            DataKamar dK = new DataKamar(no_kamar, lantai, fasilitas, harga);
            boolean createSuccess = dK.create();

            if (createSuccess) {
                // Notifikasi jika berhasil menambahkan data
                JOptionPane.showMessageDialog(null, "Data kamar berhasil ditambahkan!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            } else {
                // Notifikasi jika gagal menambahkan data
                JOptionPane.showMessageDialog(null, "Gagal menambahkan data kamar.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_CreateActionPerformed

    private void NoKamarBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoKamarBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NoKamarBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateDataKamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateDataKamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateDataKamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateDataKamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateDataKamar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton Create;
    private javax.swing.JLabel CreateDataKamar;
    private javax.swing.JTextField FasilitasBox;
    private javax.swing.JComboBox<String> HargaBox;
    private javax.swing.JLabel LabelFasilitas;
    private javax.swing.JLabel LabelHarga;
    private javax.swing.JLabel LabelLantai;
    private javax.swing.JLabel LabelNoKamar;
    private javax.swing.JComboBox<String> LantaiBox;
    private javax.swing.JComboBox<String> NoKamarBox;
    // End of variables declaration//GEN-END:variables
}
