/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFrame;

import asrama.DataKamar;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class DeleteDataKamar extends javax.swing.JFrame {

    /**
     * Creates new form DeleteDataKamar
     */
    public DeleteDataKamar() {
        initComponents();
        DataKamar dK = new DataKamar(null, null, null, 0);
        dK.setJComboBoxRuang(NoKamarBox);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelHatiHati = new javax.swing.JLabel();
        LabelPeringatan = new javax.swing.JLabel();
        LabelNoKamar = new javax.swing.JLabel();
        NoKamarBox = new javax.swing.JComboBox<>();
        Delete = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        DeleteDataKamar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelHatiHati.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        LabelHatiHati.setText("Hati - Hati !!!");
        getContentPane().add(LabelHatiHati, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 280, -1, -1));

        LabelPeringatan.setText("Data tidak dapat dipulihkan kembali.");
        getContentPane().add(LabelPeringatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 310, -1, -1));

        LabelNoKamar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LabelNoKamar.setText("No.Kamar");
        getContentPane().add(LabelNoKamar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 90, 40));

        NoKamarBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "K01", "K02", "K03", "K04", "K05", "K06", "K07", "K08", "K09", "K10" }));
        getContentPane().add(NoKamarBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 190, 40));

        Delete.setBackground(new java.awt.Color(204, 255, 204));
        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        getContentPane().add(Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 220, 110, 40));

        Back.setBackground(new java.awt.Color(204, 255, 255));
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 480, 100, 40));

        DeleteDataKamar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/7.jpg"))); // NOI18N
        DeleteDataKamar.setText("jLabel1");
        DeleteDataKamar.setPreferredSize(new java.awt.Dimension(500, 530));
        getContentPane().add(DeleteDataKamar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
        String no_kamar = (String) NoKamarBox.getSelectedItem();

        if (no_kamar == null || no_kamar.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Pilih data kamar yang ingin dihapus.", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        DataKamar dK = new DataKamar(no_kamar, null, null, 0);
        boolean deleteSuccess = dK.hapus();

        if (deleteSuccess) {
            // Notifikasi jika berhasil menghapus data
            JOptionPane.showMessageDialog(null, "Data kamar berhasil dihapus!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
        } else {
            // Notifikasi jika gagal menghapus data atau data tidak ditemukan
            JOptionPane.showMessageDialog(null, "Gagal menghapus data kamar atau data tidak ditemukan.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
         dK.setJComboBoxRuang(NoKamarBox);

    }//GEN-LAST:event_DeleteActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        AwalCRUD_DataKamar ADK = new AwalCRUD_DataKamar();
        this.dispose();;
        ADK.setVisible(true);
    }//GEN-LAST:event_BackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteDataKamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteDataKamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteDataKamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteDataKamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteDataKamar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton Delete;
    private javax.swing.JLabel DeleteDataKamar;
    private javax.swing.JLabel LabelHatiHati;
    private javax.swing.JLabel LabelNoKamar;
    private javax.swing.JLabel LabelPeringatan;
    private javax.swing.JComboBox<String> NoKamarBox;
    // End of variables declaration//GEN-END:variables
}
