/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFrame;

import asrama.DataPenghuni;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class DeleteDataPenghuni extends javax.swing.JFrame {

    /**
     * Creates new form DeleteDataPenghuni
     */
    public DeleteDataPenghuni() {
        initComponents();
        DataPenghuni dP = new DataPenghuni(null, null, null, null, null, null);
        dP.setJComboBoxPenghuni(jComboBox1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelIdPenghuni = new javax.swing.JLabel();
        LabelHatiHati = new javax.swing.JLabel();
        LabelPeringatan = new javax.swing.JLabel();
        Delete = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        DeleteDataPenghuni = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelIdPenghuni.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LabelIdPenghuni.setText("ID_Penghuni");
        getContentPane().add(LabelIdPenghuni, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 80, -1));

        LabelHatiHati.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        LabelHatiHati.setText("Hati - Hati !!!");
        getContentPane().add(LabelHatiHati, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 280, -1, 20));

        LabelPeringatan.setText("Data tidak dapat dipulihkan kembali.");
        getContentPane().add(LabelPeringatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 310, -1, -1));

        Delete.setBackground(new java.awt.Color(204, 255, 204));
        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        getContentPane().add(Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, 110, 40));

        Back.setBackground(new java.awt.Color(204, 255, 255));
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 480, 90, 40));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 210, 50));

        DeleteDataPenghuni.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/12.jpg"))); // NOI18N
        DeleteDataPenghuni.setText("jLabel1");
        DeleteDataPenghuni.setPreferredSize(new java.awt.Dimension(500, 530));
        getContentPane().add(DeleteDataPenghuni, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        AwalCRUD_DataPenghuni ADP = new AwalCRUD_DataPenghuni();
        this.dispose();
        ADP.setVisible(true);
    }//GEN-LAST:event_BackActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:

        String idP = (String) jComboBox1.getSelectedItem();

        // Check if the combo box is empty
        if (idP == null || idP.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Pilih data Penghuni yang ingin dihapus.", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        DataPenghuni dP = new DataPenghuni(idP, null, null, null, null, null);
        boolean deleteSuccess = dP.hapus();

        if (deleteSuccess) {
            // Notifikasi jika berhasil menghapus data
            JOptionPane.showMessageDialog(null, "Data Penghuni berhasil dihapus!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
        } else {
            // Notifikasi jika gagal menghapus data atau data tidak ditemukan
            JOptionPane.showMessageDialog(null, "Gagal menghapus data Penghuni atau data tidak ditemukan.", "Error", JOptionPane.ERROR_MESSAGE);
        }

        dP.setJComboBoxPenghuni(jComboBox1);
    }//GEN-LAST:event_DeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteDataPenghuni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteDataPenghuni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteDataPenghuni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteDataPenghuni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteDataPenghuni().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton Delete;
    private javax.swing.JLabel DeleteDataPenghuni;
    private javax.swing.JLabel LabelHatiHati;
    private javax.swing.JLabel LabelIdPenghuni;
    private javax.swing.JLabel LabelPeringatan;
    private javax.swing.JComboBox<String> jComboBox1;
    // End of variables declaration//GEN-END:variables
}
