/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFrame;

/**
 *
 * @author User
 */
public class MenuAdmin extends javax.swing.JFrame {

    /**
     * Creates new form MenuAdmin
     */
    public MenuAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuDataPenghuni = new javax.swing.JButton();
        MenuDataKamar = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        TampilanMenu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MenuDataPenghuni.setBackground(new java.awt.Color(204, 255, 204));
        MenuDataPenghuni.setText("Data Penghuni");
        MenuDataPenghuni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuDataPenghuniActionPerformed(evt);
            }
        });
        getContentPane().add(MenuDataPenghuni, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 160, 40));

        MenuDataKamar.setBackground(new java.awt.Color(204, 255, 204));
        MenuDataKamar.setText("Data Kamar");
        MenuDataKamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuDataKamarActionPerformed(evt);
            }
        });
        getContentPane().add(MenuDataKamar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 350, 160, 40));

        BackButton.setBackground(new java.awt.Color(204, 255, 255));
        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        getContentPane().add(BackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 480, 90, 40));

        TampilanMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/2.jpg"))); // NOI18N
        TampilanMenu.setText("jLabel1");
        TampilanMenu.setPreferredSize(new java.awt.Dimension(500, 530));
        getContentPane().add(TampilanMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 940, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuDataPenghuniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuDataPenghuniActionPerformed
        // TODO add your handling code here:
        AwalCRUD_DataPenghuni dP = new AwalCRUD_DataPenghuni();
        this.dispose();
        dP.setVisible(true);
    }//GEN-LAST:event_MenuDataPenghuniActionPerformed

    private void MenuDataKamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuDataKamarActionPerformed
        // TODO add your handling code here:
        AwalCRUD_DataKamar dk = new AwalCRUD_DataKamar();
        this.dispose();
        dk.setVisible(true);
    }//GEN-LAST:event_MenuDataKamarActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        Login login = new Login();
        this.dispose();
        login.setVisible(true);
    }//GEN-LAST:event_BackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton MenuDataKamar;
    private javax.swing.JButton MenuDataPenghuni;
    private javax.swing.JLabel TampilanMenu;
    // End of variables declaration//GEN-END:variables
}
