/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFrame;

import asrama.DataKamar;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class UpdateDataKamar extends javax.swing.JFrame {

    /**
     * Creates new form UpdateDataKamar
     */
    public UpdateDataKamar() {
        initComponents();
        DataKamar dK = new DataKamar(null, null, null, 0);
        dK.setJComboBoxRuang(NoKamarBox);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelNoKamar = new javax.swing.JLabel();
        LabelFasilitasBaru = new javax.swing.JLabel();
        LabelHargaBaru = new javax.swing.JLabel();
        NoKamarBox = new javax.swing.JComboBox<>();
        FasilitasBaruBox = new javax.swing.JTextField();
        HargaBaruBox = new javax.swing.JComboBox<>();
        Update = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        UpdateDataKamar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelNoKamar.setText("No.Kamar");
        getContentPane().add(LabelNoKamar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 70, 20));

        LabelFasilitasBaru.setText("Fasilitas Baru");
        getContentPane().add(LabelFasilitasBaru, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 90, 30));

        LabelHargaBaru.setText("Harga Baru");
        getContentPane().add(LabelHargaBaru, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 70, 20));

        NoKamarBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "K01", "K02", "K03", "K04", "K05", "K06", "K07", "K08", "K09", "K10" }));
        getContentPane().add(NoKamarBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 250, 30));
        getContentPane().add(FasilitasBaruBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 250, 30));

        HargaBaruBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "350000", "500000", "750000", "1000000" }));
        getContentPane().add(HargaBaruBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 250, 30));

        Update.setBackground(new java.awt.Color(204, 255, 204));
        Update.setText("Update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });
        getContentPane().add(Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 250, 110, 40));

        Back.setBackground(new java.awt.Color(204, 255, 255));
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 480, 90, 40));

        UpdateDataKamar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/6.jpg"))); // NOI18N
        UpdateDataKamar.setText("jLabel1");
        UpdateDataKamar.setPreferredSize(new java.awt.Dimension(500, 530));
        getContentPane().add(UpdateDataKamar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
       // TODO add your handling code here:
        String no_kamar = (String) NoKamarBox.getSelectedItem();
        String fasilitas = FasilitasBaruBox.getText();
        int harga = Integer.parseInt(String.valueOf(HargaBaruBox.getSelectedItem()));

        DataKamar dK = new DataKamar(no_kamar, null, fasilitas, harga);
        boolean updateSuccess = dK.update();

        if (updateSuccess) {
            if (dK.isDataChanged()) {
                JOptionPane.showMessageDialog(null, "Data kamar berhasil diubah!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Tidak ada perubahan yang perlu disimpan.", "Info", JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Gagal mengubah data kamar.", "Info", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_UpdateActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        AwalCRUD_DataKamar ADK = new AwalCRUD_DataKamar();
        this.dispose();
        ADK.setVisible(true);
    }//GEN-LAST:event_BackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateDataKamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateDataKamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateDataKamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateDataKamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateDataKamar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JTextField FasilitasBaruBox;
    private javax.swing.JComboBox<String> HargaBaruBox;
    private javax.swing.JLabel LabelFasilitasBaru;
    private javax.swing.JLabel LabelHargaBaru;
    private javax.swing.JLabel LabelNoKamar;
    private javax.swing.JComboBox<String> NoKamarBox;
    private javax.swing.JButton Update;
    private javax.swing.JLabel UpdateDataKamar;
    // End of variables declaration//GEN-END:variables
}
