/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFrame;

import asrama.DataKamar;
import asrama.DataPenghuni;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class UpdateDataPenghuni extends javax.swing.JFrame {

    /**
     * Creates new form UpdateDataPenghuni
     */
    public UpdateDataPenghuni() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelID = new javax.swing.JLabel();
        LabelNamaBaru = new javax.swing.JLabel();
        LabelAlamatBaru = new javax.swing.JLabel();
        LabelInstansiBaru = new javax.swing.JLabel();
        IdBox = new javax.swing.JTextField();
        NamaBaruBox = new javax.swing.JTextField();
        AlamatBaruBox = new javax.swing.JTextField();
        InstansiBaruBox = new javax.swing.JTextField();
        NoHpBaruBox = new javax.swing.JTextField();
        Update = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        LabelNoHPBaru1 = new javax.swing.JLabel();
        UpdateDataPenghuni = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelID.setText("ID");
        getContentPane().add(LabelID, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 70, 20));

        LabelNamaBaru.setText("Nama Baru");
        getContentPane().add(LabelNamaBaru, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 80, 30));

        LabelAlamatBaru.setText("Alamat Baru");
        getContentPane().add(LabelAlamatBaru, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 80, 30));

        LabelInstansiBaru.setText("Instansi Baru");
        getContentPane().add(LabelInstansiBaru, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, 80, 20));

        IdBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdBoxActionPerformed(evt);
            }
        });
        getContentPane().add(IdBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 182, 190, 40));
        getContentPane().add(NamaBaruBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 190, 40));
        getContentPane().add(AlamatBaruBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 190, 40));
        getContentPane().add(InstansiBaruBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, 200, 40));
        getContentPane().add(NoHpBaruBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, 200, 40));

        Update.setBackground(new java.awt.Color(204, 255, 204));
        Update.setText("Update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });
        getContentPane().add(Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 260, 100, 40));

        Back.setBackground(new java.awt.Color(204, 255, 255));
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 470, 80, 40));

        LabelNoHPBaru1.setText("No.HP Baru");
        getContentPane().add(LabelNoHPBaru1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, 80, 20));

        UpdateDataPenghuni.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/11.jpg"))); // NOI18N
        UpdateDataPenghuni.setText("jLabel1");
        UpdateDataPenghuni.setPreferredSize(new java.awt.Dimension(500, 530));
        getContentPane().add(UpdateDataPenghuni, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IdBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdBoxActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        AwalCRUD_DataPenghuni ADP = new AwalCRUD_DataPenghuni();
        this.dispose();
        ADP.setVisible(true);
    }//GEN-LAST:event_BackActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here:
        String id = IdBox.getText();
String nama = NamaBaruBox.getText();
String alamat = AlamatBaruBox.getText();
String instansi = InstansiBaruBox.getText();
String noHp = NoHpBaruBox.getText();

// Check if any of the fields is empty
if (id.isEmpty() || nama.isEmpty() || alamat.isEmpty() || instansi.isEmpty() || noHp.isEmpty()) {
    // Notifikasi jika ada field yang kosong
    JOptionPane.showMessageDialog(null, "Semua field harus diisi!", "Peringatan", JOptionPane.WARNING_MESSAGE);
} else {
    DataPenghuni dP = new DataPenghuni(id, nama, alamat, instansi, noHp, null);
    boolean updateSuccess = dP.update();

    if (updateSuccess && dP.isDataChanged()) {
        // Notifikasi jika berhasil mengubah data
        JOptionPane.showMessageDialog(null, "Data Penghuni berhasil diubah!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
    } else if (updateSuccess) {
        // Notifikasi jika tidak ada perubahan
        JOptionPane.showMessageDialog(null, "Tidak ada perubahan yang perlu disimpan.", "Info", JOptionPane.INFORMATION_MESSAGE);
    }
}
    }//GEN-LAST:event_UpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateDataPenghuni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateDataPenghuni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateDataPenghuni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateDataPenghuni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateDataPenghuni().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AlamatBaruBox;
    private javax.swing.JButton Back;
    private javax.swing.JTextField IdBox;
    private javax.swing.JTextField InstansiBaruBox;
    private javax.swing.JLabel LabelAlamatBaru;
    private javax.swing.JLabel LabelID;
    private javax.swing.JLabel LabelInstansiBaru;
    private javax.swing.JLabel LabelNamaBaru;
    private javax.swing.JLabel LabelNoHPBaru1;
    private javax.swing.JTextField NamaBaruBox;
    private javax.swing.JTextField NoHpBaruBox;
    private javax.swing.JButton Update;
    private javax.swing.JLabel UpdateDataPenghuni;
    // End of variables declaration//GEN-END:variables
}
